colors:
  primary:
    background: *bg
    foreground: *fg
    bright_foreground: *fg
    dim_foreground: *fg
  normal:
    black: *d
    red: *r
    green: *g
    yellow: *y
    blue: *b
    magenta: *m
    cyan: *c
    white: *l
  bright:
    black: *dd
    red: *rr
    green: *gg
    yellow: *yy
    blue: *bb
    magenta: *mm
    cyan: *cc
    white: *ll
  dim:
    black: *dd
    red: *rr
    green: *gg
    yellow: *yy
    blue: *bb
    magenta: *mm
    cyan: *cc
    white: *ll
  cursor:
    cursor: *fg
    text: *bg
  vi_mode_cursor:
    cursor: *fg
    text: *bg
  selection:
    text: *fg
    background: *bb
  search:
    matches:
      background: *gg
      foreground: *fg
    focused_match:
      background: *yy
      foreground: *fg
    bar:
      background: *bg
      foreground: *fg
